swagger: "2.0"
info:
  version: "18.10"
  title: fiberfy-server backend
# during dev, should point to your local machine
host: api.fiberfy.guifi.net
# basePath prefixes all resource paths 
basePath: /api/v1/
# 
schemes:
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /auth/loginLDAP:
    post:
      description: Returns a JWT token to the caller
      # used as the method name of the controller
      operationId: authLoginLDAP
      parameters:
        - name: username
          in: query
          description: The ldap username
          required: true
          type: string
        - name: password
          in: query
          description: The ldap password
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
